language: cpp

compiler:
 - clang
 - gcc

os:
 - osx
 - linux

matrix:
  exclude:
     - os: osx
       compiler: gcc

before_install:
 - true

install:
 - true

before_script:
 - make

script:
 - make test
